
############################
### MONITORS & WORSPACES ###
############################

source = /home/amine/.config/hypr/hyprland/monitors-workspaces.conf

###############################
### MY PROGRAMS & AUTOSTART ###
###############################

source = /home/amine/.config/hypr/hyprland/programs.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

source = /home/amine/.config/hypr/hyprland/env.conf

#####################
### LOOK AND FEEL ###
#####################

source = /home/amine/.config/hypr/hyprland/theme.conf

#############
### INPUT ###
#############

source = /home/amine/.config/hypr/hyprland/input.conf

###################
### KEYBINDINGS ###
###################

source = /home/amine/.config/hypr/hyprland/keybindings.conf

############### 
### WINDOWS ###
###############

source = /home/amine/.config/hypr/hyprland/windows.conf

exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = flatpak run com.dec05eba.gpu_screen_recorder gsr-ui
exec-once = hypridle
exec-once = sleep 0.5 && hyprlock
