# ===== RANDOM COLORED PIXEL POKEMON =====

image {
    monitor =

    path = /home/amine/.cache/hyprlock-pokemon.png

    size = 350

    rounding = 0
    border_size = 0
    rotate = 0

    position = -650, -10

    halign = center
    valign = center
}
