general {
    # DBus lock request
    lock_cmd = pidof hyprlock || /home/amine/.config/hypr/scripts/hyprlock-with-pokemon.sh

    # Lid close / suspend:
    # generate a fresh Pokemon, then lock
    before_sleep_cmd = pidof hyprlock || /home/amine/.config/hypr/scripts/hyprlock-with-pokemon.sh

    # Restore screen after resume
    after_sleep_cmd = hyprctl dispatch dpms on

    # Wait until the Wayland lockscreen has actually locked
    inhibit_sleep = 3
}
