# Default Programs
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun

# Autostart Progams
exec-once = awww-daemon
exec-once = waybar
exec-once = flatpak run com.dec05eba.gpu_screen_recorder gsr-ui