general {
    border_size = 0
    gaps_in = 10
    gaps_out = 20
    gaps_workspaces = 0
    col.active_border = rgb(DBD4AF) 45deg
    col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
}

decoration {
    rounding = 10
    rounding_power = 2.0
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 8
        passes = 2
        new_optimizations = true
        ignore_opacity = false
        noise = 0.02
        contrast = 0.85
        brightness = 0.65
    }

    shadow {
        enabled = true
        range = 10
        render_power = 3
        ignore_window = true
        color = 0xcc000000
        offset = 0 0
        scale = 1.0
    }

    dim_strength = 0.3
    dim_around = 0.6
}

animations {
    enabled = yes
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    animation = workspaces, 1, 2, easeInOutCubic, slidevert
    animation = workspacesIn, 1, 2, easeInOutCubic, slidevert
    animation = workspacesOut, 1, 2, easeInOutCubic, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    mfact = 0.55
    new_status = master
}

group {
    col.border_active = rgb(679AC9)
    col.border_inactive = rgb(919899)

    groupbar {
        font_family = sans-serif
        font_size = 11
        gradients = true
        render_titles = true
        scrolling = true
        text_color = rgb(d0dadb)
        col.active = rgb(DBD4AF)
        col.inactive = rgb(919899)
    }
}

misc {
    animate_mouse_windowdragging = true
    focus_on_activate = true
    background_color = rgb(1c2222)
    disable_hyprland_logo = false
    force_default_wallpaper = 1
}

cursor {
    inactive_timeout = 5
    no_warps = false
    hide_on_key_press = false
    hide_on_touch = true
}
